{
    "openapi": "3.0.0",
    "info": {
        "title": "Exasol Extension Manager REST-API",
        "description": "Managed extensions and instances of extensions",
        "version": "1.0"
    },
    "paths": {
        "/api/v1/extensions": {
            "summary": "List available extensions",
            "description": "Get a list of all available extensions, i.e. extensions that can be installed.",
            "get": {
                "tags": [
                    "Extension"
                ],
                "summary": "List available extensions",
                "description": "Get a list of all available extensions, i.e. extensions that can be installed.",
                "operationId": "ListAvailableExtensions",
                "responses": {
                    "200": {
                        "description": "List of extensions",
                        "content": {
                            "application/json": {
                                "schema": {
                                    
                                    "$ref": "#/components/schemas/ExtensionsResponse"
                                },
                                "example": {
                                    "extensions": [
                                        {
                                            "id": "s3-vs",
                                            "name": "S3 Virtual Schema",
                                            "description": "...",
                                            "installableVersions": [
                                                "1.0.0",
                                                "1.2.0"
                                            ]
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "default": {
                        "description": "Default error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    
                                    "$ref": "#/components/schemas/APIError"
                                },
                                "example": {
                                    "code": 500,
                                    "message": "Something went wrong.",
                                    "requestID": "Rn3x8gcEInnHt205B4c7QZ",
                                    "timestamp": "2021-01-02T15:04:05Z07:00"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "DbUsernamePassword": []
                    },
                    {
                        "DbAccessToken": []
                    }
                ],
                "parameters": [
                    {
                        "name": "dbHost",
                        "in": "query",
                        "description": "Exasol database hostname",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "dbPort",
                        "in": "query",
                        "description": "Exasol database port number",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ]
            }
        },
        "/api/v1/installations": {
            "summary": "List installed extensions",
            "description": "Get a list of all installed extensions.",
            "get": {
                "tags": [
                    "Extension"
                ],
                "summary": "List installed extensions",
                "description": "Get a list of all installed extensions.",
                "operationId": "ListInstalledExtensions",
                "responses": {
                    "200": {
                        "description": "List of extensions",
                        "content": {
                            "application/json": {
                                "schema": {
                                    
                                    "$ref": "#/components/schemas/InstallationsResponse"
                                },
                                "example": {
                                    "installations": [
                                        {
                                            "name": "s3-vs",
                                            "version": "1.0.0",
                                            "instanceParameters": null
                                        },
                                        {
                                            "name": "s3-vs",
                                            "version": "1.1.0",
                                            "instanceParameters": null
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "default": {
                        "description": "Default error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    
                                    "$ref": "#/components/schemas/APIError"
                                },
                                "example": {
                                    "code": 500,
                                    "message": "Something went wrong.",
                                    "requestID": "Rn3x8gcEInnHt205B4c7QZ",
                                    "timestamp": "2021-01-02T15:04:05Z07:00"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "DbAccessToken": []
                    },
                    {
                        "DbUsernamePassword": []
                    }
                ],
                "parameters": [
                    {
                        "name": "dbHost",
                        "in": "query",
                        "description": "Exasol database hostname",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "dbPort",
                        "in": "query",
                        "description": "Exasol database port number",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ]
            },
            "put": {
                "tags": [
                    "Extension"
                ],
                "summary": "Install an extension.",
                "description": "This installs an extension in a given version, e.g. by creating Adapter Scripts.",
                "operationId": "InstallExtension",
                "responses": {
                    "204": {
                        "description": "OK"
                    },
                    "default": {
                        "description": "Default error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    
                                    "$ref": "#/components/schemas/APIError"
                                },
                                "example": {
                                    "code": 500,
                                    "message": "Something went wrong.",
                                    "requestID": "Rn3x8gcEInnHt205B4c7QZ",
                                    "timestamp": "2021-01-02T15:04:05Z07:00"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "DbUsernamePassword": []
                    },
                    {
                        "DbAccessToken": []
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/InstallExtensionRequest"
                            },
                            "example": {
                                "ExtensionId": "",
                                "ExtensionVersion": ""
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "dbHost",
                        "in": "query",
                        "description": "Exasol database hostname",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "dbPort",
                        "in": "query",
                        "description": "Exasol database port number",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ]
            }
        },
        "/api/v1/instances": {
            "summary": "Create an instance of an extension.",
            "description": "This creates a new instance of an extension, e.g. a virtual schema.",
            "put": {
                "tags": [
                    "Instance"
                ],
                "summary": "Create an instance of an extension.",
                "description": "This creates a new instance of an extension, e.g. a virtual schema.",
                "operationId": "CreateInstance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    
                                    "$ref": "#/components/schemas/CreateInstanceResponse"
                                },
                                "example": {
                                    "instanceName": "new-instance-name"
                                }
                            }
                        }
                    },
                    "default": {
                        "description": "Default error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    
                                    "$ref": "#/components/schemas/APIError"
                                },
                                "example": {
                                    "code": 500,
                                    "message": "Something went wrong.",
                                    "requestID": "Rn3x8gcEInnHt205B4c7QZ",
                                    "timestamp": "2021-01-02T15:04:05Z07:00"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "DbUsernamePassword": []
                    },
                    {
                        "DbAccessToken": []
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateInstanceRequest"
                            },
                            "example": {
                                "extensionId": "s3-vs",
                                "extensionVersion": "1.1.0",
                                "parameterValues": [
                                    {
                                        "name": "param1",
                                        "value": "value1"
                                    }
                                ]
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "dbHost",
                        "in": "query",
                        "description": "Exasol database hostname",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "dbPort",
                        "in": "query",
                        "description": "Exasol database port number",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "DbAccessToken": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            },
            "DbUsernamePassword": {
                "type": "http",
                "scheme": "basic"
            }
        },
        "schemas": {
            "APIError": {
                "required": [
                    "code",
                    "message"
                ],
                "properties": {
                    "code": {
                        "type": "integer"
                    },
                    "message": {
                        "type": "string"
                    },
                    "requestID": {
                        "type": "string"
                    },
                    "timestamp": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "apiID": {
                        "type": "string"
                    }
                },
                "additionalProperties": false,
                "type": "object"
            },
            "CreateInstanceRequest": {
                "required": [
                    "extensionId",
                    "extensionVersion",
                    "parameterValues"
                ],
                "properties": {
                    "extensionId": {
                        "type": "string"
                    },
                    "extensionVersion": {
                        "type": "string"
                    },
                    "parameterValues": {
                        "items": {
                            
                            "$ref": "#/components/schemas/ParameterValue"
                        },
                        "type": "array"
                    }
                },
                "additionalProperties": false,
                "type": "object"
            },
            "CreateInstanceResponse": {
                "required": [
                    "instanceName"
                ],
                "properties": {
                    "instanceName": {
                        "type": "string"
                    }
                },
                "additionalProperties": false,
                "type": "object"
            },
            "ExtensionsResponse": {
                "required": [
                    "extensions"
                ],
                "properties": {
                    "extensions": {
                        "items": {
                            
                            "$ref": "#/components/schemas/ExtensionsResponseExtension"
                        },
                        "type": "array"
                    }
                },
                "additionalProperties": false,
                "type": "object"
            },
            "ExtensionsResponseExtension": {
                "required": [
                    "id",
                    "name",
                    "description",
                    "installableVersions"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "installableVersions": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array"
                    }
                },
                "additionalProperties": false,
                "type": "object"
            },
            "InstallExtensionRequest": {
                "required": [
                    "ExtensionId",
                    "ExtensionVersion"
                ],
                "properties": {
                    "ExtensionId": {
                        "type": "string"
                    },
                    "ExtensionVersion": {
                        "type": "string"
                    }
                },
                "additionalProperties": false,
                "type": "object"
            },
            "InstallationsResponse": {
                "required": [
                    "installations"
                ],
                "properties": {
                    "installations": {
                        "items": {
                            
                            "$ref": "#/components/schemas/InstallationsResponseInstallation"
                        },
                        "type": "array"
                    }
                },
                "additionalProperties": false,
                "type": "object"
            },
            "InstallationsResponseInstallation": {
                "required": [
                    "name",
                    "version",
                    "instanceParameters"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "version": {
                        "type": "string"
                    },
                    "instanceParameters": {
                        "items": {
                            "additionalProperties": true
                        },
                        "type": "array"
                    }
                },
                "additionalProperties": false,
                "type": "object"
            },
            "ParameterValue": {
                "required": [
                    "name",
                    "value"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "value": {
                        "type": "string"
                    }
                },
                "additionalProperties": false,
                "type": "object"
            }
        }
    },
    "tags": [
        {
            "name": "Extension",
            "description": "Calls to list, install and uninstall extensions"
        },
        {
            "name": "Instance",
            "description": "Calls to list, create and remove instances of an extension"
        }
    ]
}